# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.srcs/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0.xci
# IP: The module: 'mb_usb_spi_usb_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_spi_usb_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_spi_usb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_spi_usb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_spi_usb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.srcs/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0.xci
# IP: The module: 'mb_usb_spi_usb_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_spi_usb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_spi_usb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_spi_usb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_6/Lab_6.2/lab_6.2_sid/lab_6.2_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_spi_usb_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
