# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/ECE_385/Lab_6/Lab_6.1/lab_6.1_anna/lab_6.1_anna.srcs/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_1/mb_block_axi_gpio_1_1.xci
# IP: The module: 'mb_block_axi_gpio_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE_385/Lab_6/Lab_6.1/lab_6.1_anna/lab_6.1_anna.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_1/mb_block_axi_gpio_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE_385/Lab_6/Lab_6.1/lab_6.1_anna/lab_6.1_anna.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_1/mb_block_axi_gpio_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE_385/Lab_6/Lab_6.1/lab_6.1_anna/lab_6.1_anna.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_1/mb_block_axi_gpio_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/ECE_385/Lab_6/Lab_6.1/lab_6.1_anna/lab_6.1_anna.srcs/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_1/mb_block_axi_gpio_1_1.xci
# IP: The module: 'mb_block_axi_gpio_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECE_385/Lab_6/Lab_6.1/lab_6.1_anna/lab_6.1_anna.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_1/mb_block_axi_gpio_1_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE_385/Lab_6/Lab_6.1/lab_6.1_anna/lab_6.1_anna.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_1/mb_block_axi_gpio_1_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ECE_385/Lab_6/Lab_6.1/lab_6.1_anna/lab_6.1_anna.gen/sources_1/bd/mb_block/ip/mb_block_axi_gpio_1_1/mb_block_axi_gpio_1_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_axi_gpio_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
