# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/sidra/Documents/GitHub/ECE_385/Lab_7/7.1/lab7.1_sid/lab7.1_sid.srcs/sources_1/bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0.xci
# IP: The module: 'mb_usb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_7/7.1/lab7.1_sid/lab7.1_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/sidra/Documents/GitHub/ECE_385/Lab_7/7.1/lab7.1_sid/lab7.1_sid.srcs/sources_1/bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0.xci
# IP: The module: 'mb_usb_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sidra/Documents/GitHub/ECE_385/Lab_7/7.1/lab7.1_sid/lab7.1_sid.gen/sources_1/bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_usb_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
